### ISSUE TITLE
Additional Feature: show data field

### ISSUE THREAD

**Issue by jgreth** [vertexvaar/logs#5]
I would like the see the contents of the "data"-field of the log entries.

Information is stored as json formatted array in that field.

**Comment by vertexvaar** [comment]
Hi @jgreth 

if you want to inspect values that are stored in the logs `data` section you have to tick he "Show data" checkbox :wink:

**Comment by jgreth** [comment]
Oh - my - .... 
SO sorry! How could i oversee that?! Way to little coffee i guess... :) 

Sorry!

**Comment by vertexvaar** [comment]
No problem :smile:
