### ISSUE TITLE
Exception #1363778104: There is no @var annotation for property "requestId" in class "VerteXVaaR\Logs\Domain\Model\Filter"

### ISSUE THREAD

**Issue by einpraegsam** [vertexvaar/logs#6]
After installing we got an exception in backend module
TYPO3 8.7, PHP 7.0.7

**Comment by vertexvaar** [comment]
Please clear the system caches

**Comment by vertexvaar** [comment]
This is a TYPO3 v8 Problem. Investigation pending.
